version: '3'
services:
  dependencies:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dependencies
    container_name: ${DOCKER_CONTAINER_NAME}-dependencies
    image: ${DOCKER_IMAGE_NAME}-dependencies
  unit-tests:
    profiles: ['app', 'unit-tests']
    build:
      context: .
      dockerfile: ./Dockerfile
      target: unit-tests
    container_name: ${DOCKER_CONTAINER_NAME}-unit-tests
    image: ${DOCKER_IMAGE_NAME}_unit-tests
    env_file:
      - environments/.env.test
    healthcheck:
      test: ['CMD', 'npm', 'run', 'test']
      interval: 10s
      start_period: 10s
      timeout: 10s
      retries: 3
    depends_on:
      dependencies:
        condition: service_completed_successfully
  app:
    profiles: ['app']
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app
    container_name: ${DOCKER_CONTAINER_NAME}-app
    image: ${DOCKER_IMAGE_NAME}-app
    env_file:
      - environments/.env.${NODE_ENV}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    healthcheck:
      test: curl -s http://${DOCKER_CONTAINER_NAME}-app:${SERVER_PORT} || exit 1
      interval: 10s
      start_period: 10s
      timeout: 10s
      retries: 3
    depends_on:
      unit-tests:
        condition: service_completed_successfully
