sonar.host.url=http://10.10.5.233:9000
sonar.login=admin
sonar.password=AdasaSonar001
sonar.projectKey=chg-saih_chgestordocumental_backend_AYUGTrMAhFPilMDIX1W2
sonar.qualitygate.wait=true
sonar.projectName=chg-gestor-documental-back-end
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=app
sonar.exclusions=**/node_modules/**
sonar.tests=app
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true